import webpack from 'webpack';
import del from 'del';
import globby from 'globby';
import { ClearCssModulesPluginOptions } from '../common/types';
import ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';

///
// Removes *.module.scss.ts on the first execution in order prevent conflicts with *.module.scss.d.ts
// generated by css-modules-typescript-loader
///
export class ClearCssModuleDefinitionsPlugin {
  constructor(private options: ClearCssModulesPluginOptions) {
  }

  apply(compiler: webpack.Compiler) {
    const hooks = ForkTsCheckerWebpackPlugin.getCompilerHooks(compiler);

    hooks.done.tap('ClearCssModuleDefinitionsPlugin', () => {
      if (!this.options.deleted) {
        let files = globby.sync(['src/**/*.module.scss.d.ts'], { cwd: this.options.rootFolder });
        files = files.map(f => f.replace('module.scss.d.ts', 'module.scss.ts'));
        del.sync(files, { cwd: this.options.rootFolder });
        this.options.deleted = true;
      }
    });
  }
}