import webpack from 'webpack';
import { deleteSync } from 'del';
import { globbySync } from 'globby';
import { ClearCssModulesPluginOptions } from '../common/types';
import ForkTsCheckerWebpackPlugin from 'fork-ts-checker-webpack-plugin';

///
// Removes *.module.scss.ts on the first execution in order prevent conflicts with *.module.scss.d.ts
// generated by css-modules-typescript-loader
///
export class ClearCssModuleDefinitionsPlugin {

  private deleted = false;
  constructor(private options: ClearCssModulesPluginOptions) {
  }

  apply(compiler: webpack.Compiler) {
    const hooks = ForkTsCheckerWebpackPlugin.getCompilerHooks(compiler);

    hooks.issues.tap('ClearCssModuleDefinitionsPlugin', (issues: any) => {
      if (!this.deleted) {
        let files = globbySync(['src/**/*.module.scss.d.ts'], { cwd: this.options.rootFolder });
        files = files.map(f => f.replace('module.scss.d.ts', 'module.scss.ts'));
        deleteSync(files, { cwd: this.options.rootFolder });
        this.deleted = true;
      }

      return issues;
    });
  }
}
